# Generated by Django 4.0.1 on 2022-02-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='idade',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Não binario'), ('P', 'Prefiro não dizer')], max_length=1),
        ),
    ]
